export type OrderBy =
  | "clickToSignupRate"
  | "signupToPaidRate"
  | "signups"
  | "commission"
  | "sales"
  | "visits"
  | "email"
  | "name"
  | "commissionPaid"
  | "commissionUnpaid"
  | "none"
  | "code"
  | "createdAt"

export type OrderDir = "asc" | "desc"
